plugin:
    name: 'hjp.brouwerbouwer::lang.plugin.name'
    description: 'hjp.brouwerbouwer::lang.plugin.description'
    author: hjp
    icon: oc-icon-beer
    homepage: ''
navigation:
    main-menu-item:
        label: 'hjp.brouwerbouwer::lang.plugin.name'
        url: hjp/brouwerbouwer/recipes
        icon: icon-beer
        sideMenu:
            side-menu-item7:
                label: 'hjp.brouwerbouwer::lang.brewday.name'
                url: hjp/brouwerbouwer/brewday
                icon: icon-calendar
            side-menu-item5:
                label: Recipes
                url: hjp/brouwerbouwer/recipes
                icon: icon-beer
            side-menu-item:
                label: 'List of Malts and Adjucts'
                url: hjp/brouwerbouwer/listofmalts
                icon: icon-tencent-weibo
            side-menu-item3:
                label: 'hjp.brouwerbouwer::lang.hops.name'
                url: hjp/brouwerbouwer/listofhops
                icon: icon-tree
            side-menu-item2:
                label: 'Brewing gear'
                url: hjp/brouwerbouwer/gear
                icon: icon-trash-o
            side-menu-item4:
                label: 'Bjcp Style Guide'
                url: hjp/brouwerbouwer/bjcpstyleguide
                icon: icon-sitemap
            side-menu-item6:
                label: Waterprofiles
                url: hjp/brouwerbouwer/waterprofiles
                icon: icon-tint
