list: $/hjp/brouwerbouwer/models/listofhops/columns.yaml
modelClass: Hjp\Brouwerbouwer\Models\ListOfHops
title: ListOfHops
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hjp/brouwerbouwer/listofhops/update/:id'
