list: $/hjp/brouwerbouwer/models/bjcpvalues/columns.yaml
modelClass: Hjp\Brouwerbouwer\Models\BjcpValues
title: BjcpValues
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hjp/brouwerbouwer/bjcpvalues/update/:id'
