name: BjcpValues
modelClass: Hjp\Brouwerbouwer\Models\BjcpValues
form: $/hjp/brouwerbouwer/models/bjcpvalues/fields.yaml
defaultRedirect: hjp/brouwerbouwer/bjcpvalues
create:
    redirect: 'hjp/brouwerbouwer/bjcpvalues/update/:id'
    redirectClose: hjp/brouwerbouwer/bjcpvalues
update:
    redirect: hjp/brouwerbouwer/bjcpvalues
    redirectClose: hjp/brouwerbouwer/bjcpvalues
preview: {  }
