list: $/hjp/brouwerbouwer/models/listofmalts/columns.yaml
modelClass: Hjp\Brouwerbouwer\Models\ListOfMalts
title: ListOfMalts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hjp/brouwerbouwer/listofmalts/update/:id'
