<?php namespace Hjp\Brouwerbouwer\Updates;

use Seeder;
use Db;

class Seeder_hjp_brouwerbouwer_hop_adjunct_list extends Seeder
	{
	public function run()
	{
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"1",
			'variety'			=>	"Ahtanum®",
			'alpha_min'			=>	"5.7",
			'alpha_max'			=>	"6.3",
			'origin'			=>	"United States",
			'aroma'			=>	"citrus grapefruit and geranium.",
			'substitutions'			=>	'["Cascade","Amarillo®","Simcoe®","Centennial","Willamette"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"India Pale Ale, Pale Ale, Heffeweisen, American Ales, Lagers, Californian Common, Bitters",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"2",
			'variety'			=>	"Amarillo®",
			'alpha_min'			=>	"8.0",
			'alpha_max'			=>	"11.0",
			'origin'			=>	"United States",
			'aroma'			=>	"grapefruit, orange, lemon, melon, apricot and peach.",
			'substitutions'			=>	'["Cascade","Centennial","Simcoe"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"American Wheat, American Pale Ale, American IPA, Amber Wheat Beers",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"3",
			'variety'			=>	"Aramis",
			'alpha_min'			=>	"7.9",
			'alpha_max'			=>	"8.3",
			'origin'			=>	"France",
			'aroma'			=>	"spicy, herbal and subtle citrus. ",
			'substitutions'			=>	'["Willamette","Challenger","Ahtanum™","Strisselspalter","Centennial","Chinook","Hallertau","Tettnang"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pilsner, Lager, Wheat, Saison, India Pale Ale, Belgian Ales, Pale Ale, Porter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"4",
			'variety'			=>	"Aurora",
			'alpha_min'			=>	"7.0",
			'alpha_max'			=>	"8.3",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"noble characteristics.",
			'substitutions'			=>	'["Styrian Golding","Northern Brewer"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"American Pale Ale, Dark Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"5",
			'variety'			=>	"Hallertau Blanc",
			'alpha_min'			=>	"9.0",
			'alpha_max'			=>	"12.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"Floral and fruity with passion fruit, grapefruit, pineapple, grape and lemongrass overtones.",
			'substitutions'			=>	'["Nelson Sauvin"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"American IPAs, American Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"6",
			'variety'			=>	"Bobek",
			'alpha_min'			=>	"3.5",
			'alpha_max'			=>	"7.0",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"intense and pleasant with floral and pine overtones.",
			'substitutions'			=>	'["Fuggle","Willamette","Styrian Golding"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"English Ale, Extra Special Bitter, Lager, Pilsner",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"7",
			'variety'			=>	"Brewers Gold",
			'alpha_min'			=>	"5.5",
			'alpha_max'			=>	"8.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"blackcurrant, fruity, and spicy",
			'substitutions'			=>	'["Bullion","Cascade","Galena","Northern Brewer (US)","Northdown"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Ale, American Pale Ale, Bitter, Barley Wine, Imperial Stout",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"8",
			'variety'			=>	"Cascade",
			'alpha_min'			=>	"5.5",
			'alpha_max'			=>	"9.0",
			'origin'			=>	"United States",
			'aroma'			=>	"Medium intense floral, citrus and grapefruit tones",
			'substitutions'			=>	'["Centennial","Amarillo","Columbus"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pale ale, IPA, porter, barleywine	",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"9",
			'variety'			=>	"Citra®",
			'alpha_min'			=>	"11.0",
			'alpha_max'			=>	"15.0",
			'origin'			=>	"United States",
			'aroma'			=>	"grapefruit, melon, lime, gooseberry, passion fruit and lychee",
			'substitutions'			=>	'["Simcoe","Mosaic"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"American Pale Ale, American IPA, Double IPA, Amber Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"10",
			'variety'			=>	"Crystal",
			'alpha_min'			=>	"2.0",
			'alpha_max'			=>	"4.5",
			'origin'			=>	"United States",
			'aroma'			=>	"woody and green",
			'substitutions'			=>	'["Liberty","Mount Hood","German Hallertau","Ultra","Strisselspalter","Hersbrucker"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Bitter, Pilsner, Light Lager, Golden Ale, Nut Brown Ale, Pale Ale, India Pale Ale, Stout, Chocolate Stout, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"11",
			'variety'			=>	"East Kent Goldings",
			'alpha_min'			=>	"4.4",
			'alpha_max'			=>	"6.7",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"smooth and delicate with floral, lavender, spice, honey, earth, lemon, orange, grapefruit and thyme overtones.",
			'substitutions'			=>	'["U.K. Golding","First Gold","Whitbread Golding","Progress","U.S. Golding"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pale Ales, English Bitters, English Milds, English IPA, English Borwn Ales, English Barleywine, Stouts & Porters, Saisons, Christmas Ales, Golden Ales, Belgian Triple, Belgian Golden/Blonde, Irish Red, Scottish Ales,",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"12",
			'variety'			=>	"Ekuanot™",
			'alpha_min'			=>	"13.0",
			'alpha_max'			=>	"15.5",
			'origin'			=>	"United States",
			'aroma'			=>	"melon, berry, orange peel, lime, papaya, pine and fresh peppers",
			'substitutions'			=>	'["Citra","Galaxy"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pale Ales, IPAs",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"13",
			'variety'			=>	"Falconers Flight 7Cs®",
			'alpha_min'			=>	"9.0",
			'alpha_max'			=>	"10.5",
			'origin'			=>	"United States",
			'aroma'			=>	"strong fruit and citrus characteristics with layers of spicy and earthy overtones.",
			'substitutions'			=>	'["Citra","Simcoe","Amarillo","Falconers Flight","Cascade","Centennial","Chinook","Columbus","Cluster","Crystal"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"US-Style IPAs, Pale Ales, Lagers, IBAs, Black IPAs, APAs",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"14",
			'variety'			=>	"Falconers Flight®",
			'alpha_min'			=>	"9.5",
			'alpha_max'			=>	"12.0",
			'origin'			=>	"United States",
			'aroma'			=>	"distinct tropical, floral, lemon and grapefruit characteristics. ",
			'substitutions'			=>	'["Cascade","Columbus","Centennial"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"India Pale Ale, Pale Ale, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"15",
			'variety'			=>	"Fuggle",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"United States",
			'aroma'			=>	"mild, wood, mint, grass, subtle fruit",
			'substitutions'			=>	'["Fuggle (UK)","Willamette","Styrian Golding","Tettnanger (GR)"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"English Pale Ale, Belgian India Pale Ale, Extra Special Bitter, Brown Ale, Red Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"16",
			'variety'			=>	"Gold",
			'alpha_min'			=>	"3.5",
			'alpha_max'			=>	"6.5",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"honey, oregano, basil, nettle and hay",
			'substitutions'			=>	'["Nugget","Galena"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Belgian Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"17",
			'variety'			=>	"Golding",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"fragrant, floral, zesty lemon, orange and grapefruit.",
			'substitutions'			=>	'["Golding(US)","Whitbread Golding Variety (WGV)"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Winter Ale, Bitter, English Pale Ale, English Ale, Strong Ale, Copper Ale, Brown Ale, Summer Ale, Belgian Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"18",
			'variety'			=>	"Golding",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"6.5",
			'origin'			=>	"United States",
			'aroma'			=>	"delicate and sweet floral",
			'substitutions'			=>	'["East Kent Golding","Fuggle","Willamette","Savinjski Golding","Progress","Whitbread Golding"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Bitter, Pale Ale, Belgian Ale, Belgian IPA, Barley Wine, Imperial Stout, Red Ale, Irish Stout, American Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"19",
			'variety'			=>	"Hallertau",
			'alpha_min'			=>	"3.5",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"United States",
			'aroma'			=>	"noble, earthy, herbal",
			'substitutions'			=>	'["Liberty","Hallertau (US)","Hallertauer Tradition"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"German Pilsner, Pale Ale, Wheat, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"20",
			'variety'			=>	"Hallertauer Mittelfrüh",
			'alpha_min'			=>	"3.5",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"mild, but spicy with floral and citrus notes",
			'substitutions'			=>	'["Liberty","German Tradition","Ultra"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"traditional lagers, belgian ales, European ales.",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"21",
			'variety'			=>	"Hallertauer Tradition",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"7.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"earthy, grass, nectar fruits",
			'substitutions'			=>	'["Liberty","Hallertauer Mittelfruh","Ultra"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"German/European Bocks, Wheat, Hefeweizen, Pilsner, Weissbier",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"22",
			'variety'			=>	"HBC 472",
			'alpha_min'			=>	"9.0",
			'alpha_max'			=>	"11.0",
			'origin'			=>	"United States",
			'aroma'			=>	"floral, wood, coconut and distinct whiskey/bourbon",
			'purpose'			=>	"Aroma",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"23",
			'variety'			=>	"Hersbrucker",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"hay, tobacco and orange",
			'substitutions'			=>	'["Hallertauer Tradition","Spalter Select","Mount Hood","Strisselspalter","Hallertau","Liberty"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Dunkel, Strong Ale, Pilsner, Altbier, Weizenbock, Golden Ale, Marzen, Pale Ale, Wheat, Specialty Ale, Hefeweizen, Light Ale, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"24",
			'variety'			=>	"Hersbrucker Pure",
			'alpha_min'			=>	"4.2",
			'alpha_max'			=>	"5.2",
			'origin'			=>	"Germany",
			'aroma'			=>	"noble aroma",
			'substitutions'			=>	'["Hersbrucker","Hallertauer Mittelfrüh"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pilsner, Hefeweizen, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"25",
			'variety'			=>	"Huell Melon",
			'alpha_min'			=>	"6.9",
			'alpha_max'			=>	"7.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"honeydew melon and strawberry",
			'substitutions'			=>	'["Belma","Jarrylo"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Belgian Ales, Hefeweizens",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"26",
			'variety'			=>	"Liberty",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"5.0",
			'origin'			=>	"United States",
			'aroma'			=>	"noble, delicate, floral bouquet, spice",
			'substitutions'			=>	'["Hallertau","Mount Hood","Traditon"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Bock, Lager, Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"27",
			'variety'			=>	"Lublin/Lubelski",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"5.0",
			'origin'			=>	"Poland",
			'aroma'			=>	"noble character with aromas of lavendar and magnolia",
			'substitutions'			=>	'["Saaz","Sterling"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pilsner, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"28",
			'variety'			=>	"Mandarina Bavaria",
			'alpha_min'			=>	"7.0",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"citrus, fruity, tangerine",
			'substitutions'			=>	'["Columbus","Nugget","Cascade(US)"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Belgian Ale, French Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"29",
			'variety'			=>	"Mosaic®",
			'alpha_min'			=>	"10.5",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'aroma'			=>	"earthy, blueberry, tangerine papya, rose, blossoms, grass and bubble gum",
			'substitutions'			=>	'["Citra","Simcoe"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"India Pale Ale, Pale Ale, Double IPAs",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"30",
			'variety'			=>	"Motueka",
			'alpha_min'			=>	"6.5",
			'alpha_max'			=>	"7.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"crushed fresh citrus, Mojito lime, lively lemon and lime tones with undercurrents of a tropical fruit",
			'substitutions'			=>	'["Saaz","Sterling"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"European Ale, English Ale, Dark Lager, Pilsner, Belgian Ales, Lager, Maibock, Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"31",
			'variety'			=>	"Mount Hood",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"8.0",
			'origin'			=>	"United States",
			'aroma'			=>	"herbal, pungent, spicy",
			'substitutions'			=>	'["Crystal","Strisselspalter","Hersbrucker"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Hefeweizen, Doppelbock, Russian Imperial Stout, Brown Ale, Golden Ale, Pale Ale, Amber Ale, Weizenbock, India Pale Ale, Holiday Lager, Bock, American Wheat, Alt Munich Helles, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"32",
			'variety'			=>	"Pacific Hallertau",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"6.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"Citrusy, spicy, orange and floral aromas",
			'substitutions'			=>	'["Liberty"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Porter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"33",
			'variety'			=>	"Pacifica",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"orange zest marmalade, classic Hallertau characteristics with floral notes",
			'substitutions'			=>	'["Liberty"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Porter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"34",
			'variety'			=>	"Palisade®",
			'alpha_min'			=>	"6.5",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"United States",
			'aroma'			=>	"apricot, grass and clean floral characteristics",
			'substitutions'			=>	'["Styrian Golding","Willamette","Glacier","Chinook"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Golden Ale, Pale Ale, English Ales, American Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"35",
			'variety'			=>	"Riwaka",
			'alpha_min'			=>	"4.5",
			'alpha_max'			=>	"6.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"powerful tropical passionfruit with grapefruit and citrus",
			'substitutions'			=>	'["Czech Saaz"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"India Pale Ale, Pilsner, American Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"36",
			'variety'			=>	"Saaz",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"4.5",
			'origin'			=>	"Czech Republic",
			'aroma'			=>	"mild with pleasant earthy, herbal and floral character",
			'substitutions'			=>	'["Polish Lublin","US Saaz","US Sterling","Tettnang"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Bohemian-style beers, Continental lagers, Wheats, Pilsener lagers.",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"37",
			'variety'			=>	"Saaz Triploid B",
			'alpha_min'			=>	"6.5",
			'alpha_max'			=>	"8.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"citrus and tropical fruit",
			'substitutions'			=>	'["Saaz","Saaz (US)","Sterling"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"European Ale, English Ale, Dark Lager, Pilsner, Belgian Ales, Lager, Maibock, Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"38",
			'variety'			=>	"Santiam",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"7.0",
			'origin'			=>	"United States",
			'aroma'			=>	"black pepper, floral and spice",
			'substitutions'			=>	'["Tettnanger","Spalter","Spalter Select","Hallertau","Liberty"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"American Blonde Ale, American Lager, India Pale Ale, American Pale Ale, Wheat, Bock",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"39",
			'variety'			=>	"Saphir",
			'alpha_min'			=>	"2.0",
			'alpha_max'			=>	"4.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"spicy, fruity, floral with hints of tangerine",
			'substitutions'			=>	'["Hallertau Mittelfrüh","Hallertau Tradition","Spalter Select"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pilsners, German lagers, Belgian whites",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"40",
			'variety'			=>	"Savinjski Golding",
			'alpha_min'			=>	"4.5",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"noble",
			'substitutions'			=>	'["Fuggle","Willametter","Bobek"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Extra Special Bitter, Ale, Lager, Belgian Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"41",
			'variety'			=>	"Select",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"6.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"spicy, grass",
			'substitutions'			=>	'["Saaz","Tettnanger(GR)","Spalt","Hersbrucker"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Kolsch, Marzen, Lager, Pilsner, Alt, Helles, Bock",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"42",
			'variety'			=>	"Spalt",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"United States",
			'aroma'			=>	"noble characteristics, earthy, herbal",
			'substitutions'			=>	'["Saaz","Tettnanger","Spalt","Santiam","Liberty","Hallertau"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"German Ale, Lager, Pilsner, Bock, Kolsch",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"43",
			'variety'			=>	"Spalter",
			'alpha_min'			=>	"3.5",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"noble characteristics, earthy, herbal",
			'substitutions'			=>	'["Saaz","Tettnanger","Spalt","Santiam","Liberty","Hallertau"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"German Ale, Lager, Pilsner, Bock, Kolsch",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"44",
			'variety'			=>	"Spalter Select",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"spicy & grass",
			'substitutions'			=>	'["Saaz","Tettnanger","Spalt","Hersbrucker","Perle","Hallertau Tradition"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Kölsch, Belgian Ale, French Ale, Lager, Bock, Helles, Alt, Pilsner, Marzen",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"45",
			'variety'			=>	"Strisselspalt",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"5.0",
			'origin'			=>	"France",
			'aroma'			=>	"spicy, citrusy, floral, fruity and herbal",
			'substitutions'			=>	'["Liberty","Hallertau","Mt Hood","Crystal","Hersbrucker"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Lager, Saison, Blonde Ale, Amber Ale, Belgian Ale, Bock, Maibock, Golden Ale, Belgian Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"46",
			'variety'			=>	"Styrian Golding",
			'alpha_min'			=>	"4.5",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"resinous, earthy, with notes of white pepper",
			'substitutions'			=>	'["Fuggle","Willamette","Bobek"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Extra Special Bitter, Ale, Lager, Belgian Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"47",
			'variety'			=>	"Summer",
			'alpha_min'			=>	"5.6",
			'alpha_max'			=>	"6.4",
			'origin'			=>	"Australia",
			'aroma'			=>	"apricot and melon.",
			'purpose'			=>	"Aroma",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"48",
			'variety'			=>	"Sussex",
			'alpha_min'			=>	"4.3",
			'alpha_max'			=>	"5.8",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"earthy, grass, mint, citrus and vanilla",
			'substitutions'			=>	'["Progress","Whitbread Golding","Fuggle"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"English Ale, Pale Ale, Belgian Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"49",
			'variety'			=>	"Sylva",
			'alpha_min'			=>	"5.6",
			'alpha_max'			=>	"7.3",
			'origin'			=>	"Australia",
			'aroma'			=>	"floral, herbal and noble characteristics.",
			'substitutions'			=>	'["Hallertau Mittlefrüh","Helga","Saaz"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pilsner, Lager, California Common, Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"50",
			'variety'			=>	"Tahoma",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"7.5",
			'origin'			=>	"United States",
			'aroma'			=>	"lemon, grapefruit, cedar, pine, spice and pepper",
			'substitutions'			=>	'["??"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Blonde Ale, Wheat, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"51",
			'variety'			=>	"Tettnanger",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"5.0",
			'origin'			=>	"United States",
			'aroma'			=>	"Floral, spice",
			'substitutions'			=>	'["Spalter Select","Santiam","Czech Saaz","Spalter"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Bitter, Blonde Ale, Red Ale, Pilsner, Lager, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"52",
			'variety'			=>	"Tettnanger",
			'alpha_min'			=>	"3.5",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"herbal, spicy, pepper and black tea",
			'substitutions'			=>	'["Czech Saaz","Spalter","Santiam","Spalter Select","Saaz","Tettnanger (US)"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Bitter, California Blonde Ale, Red Ale, Pilsner, Lager, American Amber Ale, Winter Ale, Pale Ale, Wheat Beer, Bavarian Hefeweizen, Cream Ale, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"53",
			'variety'			=>	"Tradition",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"7.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"medium to intense floral, herbal and grassy notes",
			'substitutions'			=>	'["some fruity aromas"]',
			'purpose'			=>	"Magnum, Hersbrucker, Taurus",
			'styles'			=>	"Aroma",
			'descriptions'			=>	"Lagers, Pilsner, Bock, Wheat, Weizen ",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"54",
			'variety'			=>	"Triplepearl",
			'alpha_min'			=>	"10.3",
			'alpha_max'			=>	"11.2",
			'origin'			=>	"United States",
			'aroma'			=>	"melon, orange, resin, spice and pepper",
			'purpose'			=>	"Aroma",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"55",
			'variety'			=>	"Triskel",
			'alpha_min'			=>	"8.0",
			'alpha_max'			=>	"9.0",
			'origin'			=>	"France",
			'aroma'			=>	"spicy, strong floral, herbal, citrus",
			'substitutions'			=>	'["Strisselspalt","Ahtanum™","Centennial","Chinook","Simcoe®"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Belgian Ale, Saison, Kolsch, Pilsner, Pale Ale, India Pale Ale, Lager, Wheat",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"56",
			'variety'			=>	"Ultra",
			'alpha_min'			=>	"2.0",
			'alpha_max'			=>	"3.5",
			'origin'			=>	"United States",
			'aroma'			=>	"mild, spicy and floral bouquet",
			'substitutions'			=>	'["Tettnanger (GR)","Saaz","Hallertauer Tradition","Liberty"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Oktoberfest, Blonde Ale, Harvest Ale, Lager, Pilsner, Pale Ale, American Lager, Bock",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"57",
			'variety'			=>	"Vanguard",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"5.0",
			'origin'			=>	"United States",
			'aroma'			=>	"woody, cedary ",
			'substitutions'			=>	'["Hallertau","German Hersbrucker","Mt. Hood","Liberty"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Lagers, Pilsners, Bocks, Kolsch, Wheats, Munich Helles, Belgian-Style Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"58",
			'variety'			=>	"Wai-iti",
			'alpha_min'			=>	"2.5",
			'alpha_max'			=>	"3.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"fresh peaches, apricot, limes with top notes of mixed citrus and spice",
			'substitutions'			=>	'["Riwaka"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Pale Ale, India Pale Ale, Wheat Beer",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"59",
			'variety'			=>	"Whitbread Golding",
			'alpha_min'			=>	"5.4",
			'alpha_max'			=>	"7.7",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"Earthy, floral and botanical with sweet fruit flavors",
			'substitutions'			=>	'["Fuggle","East Kent Golding"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"Ale, Pale Ale, Bitter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"60",
			'variety'			=>	"Zythos®",
			'alpha_min'			=>	"10.0",
			'alpha_max'			=>	"12.5",
			'origin'			=>	"United States",
			'aroma'			=>	"Pineapple, citrus and mild pine character",
			'substitutions'			=>	'["Simcoe","Amarillo","Cascade"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"American Ale, IPAs, Pale Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"61",
			'variety'			=>	"Admiral",
			'alpha_min'			=>	"13.5",
			'alpha_max'			=>	"15.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	" a versatile replacement for both high alpha and dual purpose varieties.",
			'substitutions'			=>	'["English IPA","American IPA & Double IPA","Extra Special Bitter (ESB)","Bitter","Pale Ales & Red Ales","India Red Ale & India Black Ale"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"pleasant, resinous hop aroma with hints of citrus (orange) and herbal flavors.",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"62",
			'variety'			=>	"Bravo",
			'alpha_min'			=>	"15.0",
			'alpha_max'			=>	"18.0",
			'origin'			=>	"United States",
			'aroma'			=>	"orange, vanilla and floral.",
			'substitutions'			=>	'["Columbus","Zeus","Apollo","Magnum","Nugget"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"India Pale Ale, American Pale Ale, Extra Special Bitter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"63",
			'variety'			=>	"Brewers Gold",
			'alpha_min'			=>	"8.0",
			'alpha_max'			=>	"11.0",
			'origin'			=>	"United States",
			'aroma'			=>	"blackcurrant and spicy",
			'substitutions'			=>	'["Bullion","Cascade","Galena","Northern Brewer","Northdown"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"IPA",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"64",
			'variety'			=>	"Chelan",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.5",
			'origin'			=>	"United States",
			'aroma'			=>	"mild floral and citrus characteristics",
			'substitutions'			=>	'["Galena","Nugget"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"American Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"65",
			'variety'			=>	"Columbus",
			'alpha_min'			=>	"14.0",
			'alpha_max'			=>	"16.0",
			'origin'			=>	"United States",
			'aroma'			=>	"black pepper, licorice, curry and subtle citrus.",
			'substitutions'			=>	'["Zeus","Tomahawk","Chinook","Galena","Millennium","Nugget"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"American Pale Ale, IPAs & Imperial IPAs, Imperial Red Ale, Imperial Brown Ale, Barley Wine, Stout, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"66",
			'variety'			=>	"Comet",
			'alpha_min'			=>	"8.0",
			'alpha_max'			=>	"10.5",
			'origin'			=>	"United States",
			'aroma'			=>	"subtle, wild American, grassy and grapefruit.",
			'substitutions'			=>	'["Galena","Summit™"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Lager, American Ale, India Pale Ale, Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"67",
			'variety'			=>	"Galena",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'aroma'			=>	"weet fruits, pear, pineapple, blackcurrant, grapefruit, lime, gooseberry and spicy wood.",
			'substitutions'			=>	'["Nugget","Columbus","Zeus","Chinook","Pride of Ringwood","Eroica","Newport","Cluster","Brewers Gold"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Imperial Stout, Stout, India Pale Ale, Barley Wine",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"68",
			'variety'			=>	"Green Bullet",
			'alpha_min'			=>	"13.0",
			'alpha_max'			=>	"15.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"spicy, dried fruit, with lots of floral character that balance and complement pine, resin hop tones ",
			'substitutions'			=>	'["Liberty","Hallertauer","Crystal","Mount Hood","Ultra"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Bock, Saison, India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"69",
			'variety'			=>	"Hallertauer Taurus",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"16.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"* Chocolate, banana, spice, pepper, curry",
			'substitutions'			=>	'["Hallertauer Magnum","Merkur","Hercules"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Schwarzbier, Oktoberfest",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"70",
			'variety'			=>	"HBC 682",
			'alpha_min'			=>	"18.0",
			'alpha_max'			=>	"21.0",
			'origin'			=>	"United States",
			'aroma'			=>	"strong, earthy, spicy, herbal",
			'purpose'			=>	"Bittering",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"71",
			'variety'			=>	"Herkules",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"17.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"robust, hoppy, with some citrus and melon",
			'purpose'			=>	"Bittering",
			'styles'			=>	"German ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"72",
			'variety'			=>	"Magnum",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"spicy, fruity, apple, pepper",
			'substitutions'			=>	'["Hallertauer Taurus","Columbus","Nugget"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"*India Pilsner, Belgian India Pale Ale, American Ale, Blonde Ale, Pale Ale, Nut Brown Ale, Dark Ale, Pilsner, Bright Ale, Hefeweizen",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"73",
			'variety'			=>	"Magnum",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"15.5",
			'origin'			=>	"United States",
			'aroma'			=>	"bittering hop with no distinc aroma characteristics",
			'substitutions'			=>	'["Galena","German Magnum","Horizon","Northdown","Northern Brewer"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"American Pale Ale, American India Pale Ale, Strong Ale, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"74",
			'variety'			=>	"Merkur",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"sugar, pineapple, mint",
			'substitutions'			=>	'["German Magnum","German Taurus","German Tradition"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"IPAs, Lagers, Belgian Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"75",
			'variety'			=>	"Millennium",
			'alpha_min'			=>	"15.5",
			'alpha_max'			=>	"18.5",
			'origin'			=>	"United States",
			'aroma'			=>	"floral, fruity, herbal, resin, toffee and pear",
			'substitutions'			=>	'["Nugget","Columbus","Summit™","CTZ"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Stout, Ale, American Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"76",
			'variety'			=>	"Newport",
			'alpha_min'			=>	"13.5",
			'alpha_max'			=>	"17.0",
			'origin'			=>	"United States",
			'aroma'			=>	"earth, citrus, wine and balsamic",
			'substitutions'			=>	'["Brewers Gold","Fuggle","Galena","Magnum","Nugget"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Pale Ale, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"77",
			'variety'			=>	"Nugget",
			'alpha_min'			=>	"11.5",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"mild, pleasant, herbal",
			'substitutions'			=>	'["Galena","Columbus","Tomahawk","Zeus","Hallerauer Magnum","Target"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"IPA, Pale Ale, Blonde, American Wheat, ESB, APA, Imperial IPA, Irish Stout, Oktoberfest, Rye Ale, Best Bitter, EPA, Barley Wine, Strong Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"78",
			'variety'			=>	"Nugget",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'aroma'			=>	"mild, pleasant, herbal",
			'substitutions'			=>	'["Galena","Magnum","Columbus"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"India Pale Ale, Imperial India Pale Ale, Ales, Stouts, Barley Wines, Saisons, Biere de Garde",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"79",
			'variety'			=>	"Pacific Gem",
			'alpha_min'			=>	"14.0",
			'alpha_max'			=>	"17.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"spicy black pepper and berry fruit aromas with subtle notes of blackberry, floral and oak",
			'substitutions'			=>	'["Fuggle"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Strong Ale, European Lagers",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"80",
			'variety'			=>	"Pacific Sunrise",
			'alpha_min'			=>	"12.5",
			'alpha_max'			=>	"14.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"pleasant pine aromas",
			'substitutions'			=>	'["Pacific Gem"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Lager ",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"81",
			'variety'			=>	"Southern Star",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"15.5",
			'origin'			=>	"South Africa",
			'aroma'			=>	"spicy, tangy flavor with berry notes",
			'substitutions'			=>	'["Outeniqua"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Lager, Pale Ale, IPA, Stout, Barley Wine",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"82",
			'variety'			=>	"Summit™",
			'alpha_min'			=>	"15.0",
			'alpha_max'			=>	"17.0",
			'origin'			=>	"United States",
			'aroma'			=>	"pepper, incense, anise, orange, pink grapefruit and tangerine",
			'substitutions'			=>	'["Apollo","Bravo","CTZ","Zeus","Warrior","Simcoe"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"IPAs, Imperial IPAs, Pale Ales, Stouts, Barley Wines",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"83",
			'variety'			=>	"Sun",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"16.0",
			'origin'			=>	"United States",
			'aroma'			=>	"herbaceous aroma and flavor",
			'substitutions'			=>	'["Magnum","Galena","Zeus"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Barley Wine, Imperial Stout",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"84",
			'variety'			=>	"Target",
			'alpha_min'			=>	"9.5",
			'alpha_max'			=>	"12.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"green sage, spicy and peppery, and hints of citrus marmalade",
			'substitutions'			=>	'["Fuggle","Willamette"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Bitter, Pale Ale, Kentish Bitter, India Pale Ale, Brown Ale, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"85",
			'variety'			=>	"Tomahawk®",
			'alpha_min'			=>	"15.0",
			'alpha_max'			=>	"17.5",
			'origin'			=>	"United States",
			'aroma'			=>	"pungent, herbal, spicy, black pepper, licorice, curry and subtle citrus",
			'substitutions'			=>	'["Centennial","Chinook","Galena","Nugget","Millennium"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"US IPAs, US Pale Ales, Stouts, Barley Wines, Lagers",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"86",
			'variety'			=>	"Victoria",
			'alpha_min'			=>	"14.0",
			'alpha_max'			=>	"15.0",
			'origin'			=>	"Australia",
			'aroma'			=>	"tropical fruit, pine, herbal",
			'substitutions'			=>	'["Galaxy"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"Pale Ale, IPA, Stout, Porter, Red Ale, Barley Wine, Imperial IPA, Extra Pale Ale, Golden Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"87",
			'variety'			=>	"Warrior®",
			'alpha_min'			=>	"15.0",
			'alpha_max'			=>	"17.0",
			'origin'			=>	"United States",
			'aroma'			=>	"mild, resinous and subtle pine.",
			'substitutions'			=>	'["Nugget","Columbus"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"India Pale Ale, American Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"88",
			'variety'			=>	"Zeus",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"18.0",
			'origin'			=>	"United States",
			'aroma'			=>	"spicy, herbal, pungent, black pepper, licorice, and curry",
			'substitutions'			=>	'["Columbus","Centennial","Chinook","Galena","Nugget","Millennium"]',
			'purpose'			=>	"Bittering",
			'styles'			=>	"*US IPAs, US Pale Ales, Stouts, Barley Wines, Lagers",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"89",
			'variety'			=>	"Bitter Gold",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.5",
			'origin'			=>	"United States",
			'aroma'			=>	"pear, watermelon, stone fruit and fresh cut grass.",
			'substitutions'			=>	'["Galena","Nugget"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Ale, Lager, Pilsner, Bitter, India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"90",
			'variety'			=>	"Bramling Cross",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"7.8",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"strong spice, blackcurrant, loganberry and lemon",
			'substitutions'			=>	'["U.K. Kent Golding","U.K. Progress","Whitbread Golding Variety"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"ESB, bitter, pale ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"91",
			'variety'			=>	"Celeia",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"noble characteristics.",
			'substitutions'			=>	'["Saaz","Bobek","Styrian Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"English Ale, Lager, American Lager, Pilsner, English Ale, Extra Special Bitter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"92",
			'variety'			=>	"Centennial",
			'alpha_min'			=>	"9.5",
			'alpha_max'			=>	"11.5",
			'origin'			=>	"United States",
			'aroma'			=>	"lemon and floral",
			'substitutions'			=>	'["Cascade","Amarillo","chinook","Simcoe"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pale Ale, Amber Ale, American IPA, American Blonde, American Stout, American Wheat, Double IPA, Barley Wine, Red Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"93",
			'variety'			=>	"Challenger",
			'alpha_min'			=>	"6.5",
			'alpha_max'			=>	"8.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"cedar, green tea and sweet fruit",
			'substitutions'			=>	'["Perle (US)","Northern Brewer","Admiral"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Golden Ale, Barley Wine, Imperial Stout",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"94",
			'variety'			=>	"Chinook",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'aroma'			=>	"grapefruit, spice, and pine",
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"American Pale Ale & India Pale Ale, American Stout & Porter, American Amber, American Brown, American Barley Wine, American Lagers, Winter Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"95",
			'variety'			=>	"Cluster",
			'alpha_min'			=>	"5.5",
			'alpha_max'			=>	"8.5",
			'origin'			=>	"United States",
			'aroma'			=>	"floral, earthy and sweet fruit",
			'substitutions'			=>	'["Eroica","Galena"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Barley Wine, Porter, English Pale Ale, Amber Ale, Honey Ale, Cream Ale, American Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"96",
			'variety'			=>	"Dr. Rudi",
			'alpha_min'			=>	"10.0",
			'alpha_max'			=>	"12.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"resin, pine, and lemongrass.",
			'substitutions'			=>	'["Green Bullet"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lager, India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"97",
			'variety'			=>	"Ella",
			'alpha_min'			=>	"13.3",
			'alpha_max'			=>	"16.3",
			'origin'			=>	"Australia",
			'aroma'			=>	"distinct grapefruit and tropical flavor",
			'substitutions'			=>	'["Perle","Palisade"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lager, Pilsner, Pale Ale, Stout",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"98",
			'variety'			=>	"First Gold",
			'alpha_min'			=>	"5.6",
			'alpha_max'			=>	"8.7",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"smooth, with tangerine, orange marmalade, apricot, geranium and magnolia.",
			'substitutions'			=>	'["Willamette","East Kent Golding","Styrian Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Porter, English Bitter, Wheat Beer, Celtic Ale, Summer Ale, Amber Ale, Dark Amber Ale, India Pale Ale, Imperial India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"99",
			'variety'			=>	"Fuggle",
			'alpha_min'			=>	"3.0",
			'alpha_max'			=>	"5.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"delicate and pleasant mint, grass and floral tones.",
			'substitutions'			=>	'["Fuggle (US)","Willamette","Styrian Golding","Tettnanger","Newport"]',
			'purpose'			=>	"Aroma",
			'styles'			=>	"English Ale, Porter, Mild Ale, Bitter, Extra Special Bitter, Lambic, Amber Ale, Cask Ale, Stout, Oatmeal Stout, Strong Ale, Nut Brown Ale, Golden Ale, Christmas Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"100",
			'variety'			=>	"Galaxy",
			'alpha_min'			=>	"11.6",
			'alpha_max'			=>	"16.0",
			'origin'			=>	"Australia",
			'aroma'			=>	"distinct passionfruit and clean citrus aromas",
			'substitutions'			=>	'["Citra®","Amarillo®","Centennial"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pale Ale, India Pale Ale, ESB",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"101",
			'variety'			=>	"Glacier",
			'alpha_min'			=>	"3.3",
			'alpha_max'			=>	"9.7",
			'origin'			=>	"United States",
			'aroma'			=>	"plum, blackberry and wood",
			'substitutions'			=>	'["Willamette","Fuggle (US)","Tettnanger (GR)","Golding (US)"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Extra Special Bitter, India Pale Ale, Wheat Beer, American Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"102",
			'variety'			=>	"Hallertau Aroma",
			'alpha_min'			=>	"7.0",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"subtle floral with aroma of fresh zested lime",
			'substitutions'			=>	'["Hallertauer Mittelfruh"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pale Ale, Pilsner, Lager, Bitter, Bock",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"103",
			'variety'			=>	"HBC 431",
			'alpha_min'			=>	"14.0",
			'alpha_max'			=>	"16.0",
			'origin'			=>	"United States",
			'aroma'			=>	"peach, berry, tropical fruit, citrus and herbal.",
			'purpose'			=>	"Dual Purpose",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"104",
			'variety'			=>	"HBC 438",
			'alpha_min'			=>	"12.4",
			'alpha_max'			=>	"14.9",
			'origin'			=>	"United States",
			'aroma'			=>	"peachy stone fruit, tropical pineapple, and lime with herbal notes of cedar and coconut",
			'substitutions'			=>	'["exceptionally distinct and pleasant."]',
			'styles'			=>	"Dual Purpose",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"105",
			'variety'			=>	"Helga",
			'alpha_min'			=>	"5.4",
			'alpha_max'			=>	"7.3",
			'origin'			=>	"Australia",
			'aroma'			=>	"pleasant, noble characteristics, herbal, earthy",
			'substitutions'			=>	'["Hallertau"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"106",
			'variety'			=>	"Herald",
			'alpha_min'			=>	"11.0",
			'alpha_max'			=>	"13.0",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"orange, grapefruit aromas",
			'substitutions'			=>	'["Pioneer"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pale Ale, Golden Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"107",
			'variety'			=>	"Horizon",
			'alpha_min'			=>	"10.2",
			'alpha_max'			=>	"16.5",
			'origin'			=>	"United States",
			'aroma'			=>	"floral, spicy",
			'substitutions'			=>	'["Hallertauer Magnum"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Light Ale, Red Ale, Pumpkin Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"108",
			'variety'			=>	"Hüller Bitterer",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"6.3",
			'origin'			=>	"Germany",
			'aroma'			=>	"n/a",
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Schwarzbier, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"109",
			'variety'			=>	"Kohatu",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"7.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"fresh tropical fruit characters and an excellent finish and bitterness.",
			'substitutions'			=>	'["Wai-iti","Motueka"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Ale, Pale Ale, India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"110",
			'variety'			=>	"Loral®",
			'alpha_min'			=>	"11.3",
			'alpha_max'			=>	"12.2",
			'origin'			=>	"United States",
			'aroma'			=>	"very pleasant, floral, peppery, lemon-citrus and dark fruit, herbal",
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"IPA, APA, American Wheat Ales",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"111",
			'variety'			=>	"Marynka",
			'alpha_min'			=>	"9.0",
			'alpha_max'			=>	"12.0",
			'origin'			=>	"Czech Republic",
			'aroma'			=>	"earthy, herbal",
			'substitutions'			=>	'["Tettnanager(GR)"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Bitter, India Pale Ale, Pale Ale, Pilsner",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"112",
			'variety'			=>	"Mount Rainier",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"7.0",
			'origin'			=>	"United States",
			'aroma'			=>	"noble, licorice, floral",
			'substitutions'			=>	'["Hallertau","Fuggle"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lager, American Ale, Porter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"113",
			'variety'			=>	"Nelson Sauvin",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"white wine, fruity, crushed gooseberry, and grape",
			'substitutions'			=>	'["Pacific Jade","Pacifica"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"American Pale Ale, India Pale Ale, Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"114",
			'variety'			=>	"Northdown",
			'alpha_min'			=>	"6.8",
			'alpha_max'			=>	"9.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"pleasant spice cedar, pine, subtle floral and hints of berry",
			'substitutions'			=>	'["Challenger","Admiral","Target"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Blonde Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"115",
			'variety'			=>	"Northern Brewer",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"mint, pine and grass",
			'substitutions'			=>	'["Perle","Northern Brewer(US)"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Steam Beer, German Ale, German Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"116",
			'variety'			=>	"Northern Brewer",
			'alpha_min'			=>	"7.0",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"United States",
			'aroma'			=>	"evergreen, wood and mint",
			'substitutions'			=>	'["Galena","Perle","Magnum","Chinook","German Northern Brewer"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Porters, Ales, Kolsch, Munich Helles, ESBs, German Lagers, Steam beers,",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"117",
			'variety'			=>	"Opal",
			'alpha_min'			=>	"13.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"Australia",
			'aroma'			=>	"spice, pepper, citrus, with fruity, floral and herbal characteristics",
			'substitutions'			=>	'["East Kent Golding","Styrian Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pilsner, Hefeweizen, Helles, Lager, Brown Ale, Saison, Tripel, Wheat, Kolsch, Blonde Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"118",
			'variety'			=>	"Orion",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"8.5",
			'origin'			=>	"Germany",
			'substitutions'			=>	'["Perle"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Helles, Dunkel",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"119",
			'variety'			=>	"Outeniqua",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"13.5",
			'origin'			=>	"South Africa",
			'aroma'			=>	"strong, punchy, hoppy aroma",
			'substitutions'			=>	'["Southern Star"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pilsner",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"120",
			'variety'			=>	"Pacific Jade",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"fresh citrus, complex spice characters, bold herbal aromas, subtle black pepper",
			'substitutions'			=>	'["Hallertau","Magnum"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lagers, Ales,Pale Ale, India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"121",
			'variety'			=>	"Perle",
			'alpha_min'			=>	"5.0",
			'alpha_max'			=>	"7.5",
			'origin'			=>	"Germany",
			'aroma'			=>	"herbal, spicy with subtle floral, fruit and mint ",
			'substitutions'			=>	'["Perle (US)","Northern Brewer (GR)"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Hefeweizen, Belgian Strong Ale, Lager, Pilsner, Kölsch",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"122",
			'variety'			=>	"Perle",
			'alpha_min'			=>	"7.0",
			'alpha_max'			=>	"9.5",
			'origin'			=>	"United States",
			'aroma'			=>	"floral, spicy",
			'substitutions'			=>	'["Perle (GR)","Northern Brewer (GR)"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Hefeweizen, Belgian Strong Ale, Lager, Pilsner, Kölsch",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"123",
			'variety'			=>	"Phoenix",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"15.0",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"spicy, floral and chocolate",
			'substitutions'			=>	'["Northdown","Challenger","East Kent Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"India Pale Ale, Bitter, Golden Ale, Triple India Pale Ale, English Ale, Extra Special Bitter, Stout, Brown Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"124",
			'variety'			=>	"Pilgrim",
			'alpha_min'			=>	"10.0",
			'alpha_max'			=>	"13.0",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"fruit and spice with pleasant lemon, grapefruit, pear and berry flavors",
			'substitutions'			=>	'["Target","Pioneer","Challenger"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"English Pale Ale, India Pale Ale, Wheat Beer, Stout, Barley Wine, Imperial Stout",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"125",
			'variety'			=>	"Pioneer",
			'alpha_min'			=>	"8.0",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"lemon, grapefruit and hints of herbal, cedar flavors",
			'substitutions'			=>	'["East Kent Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"India Pale Ale, Red Ale, Specialty Ale, Strong Bitter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"126",
			'variety'			=>	"Polaris",
			'alpha_min'			=>	"18.0",
			'alpha_max'			=>	"23.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"mint, pineapple and menthol",
			'substitutions'			=>	'["Herkules"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Ales, Pale Ales, India Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"127",
			'variety'			=>	"Premiant",
			'alpha_min'			=>	"7.0",
			'alpha_max'			=>	"10.0",
			'origin'			=>	"Czech Republic",
			'aroma'			=>	"pleasant and mild",
			'substitutions'			=>	'["Styrian Golding","Saaz"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pilsner, Ale, Pale Ale, Belgian Ales, Belgian Pilsners",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"128",
			'variety'			=>	"Pride of Ringwood",
			'alpha_min'			=>	"9.0",
			'alpha_max'			=>	"12.0",
			'origin'			=>	"Australia",
			'aroma'			=>	"cedar, oak, herbal",
			'substitutions'			=>	'["East Kent Goldings","Centennial","Galena","Cluster"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Amber Ale, Lager, Fruit Lambic, Pale Ale, Australian Lager, Strong Ale, Golden Ale, American Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"129",
			'variety'			=>	"Progress",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"7.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"grass, mint, honey and blackcurrant",
			'substitutions'			=>	'["East Kent Goldings","Fuggle"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"English Bitters, Pale Ale, Porter, Stout, Czech Pilsner, Bock, Cask Ale, Wheat",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"130",
			'variety'			=>	"Rakau",
			'alpha_min'			=>	"10.0",
			'alpha_max'			=>	"11.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"stone fruit, fig, fresh orchard fruits, apricot, resinous pine needles",
			'substitutions'			=>	'["Amarillo","Summit"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pale Ale, Lager, Belgian Ales, IPAs",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"131",
			'variety'			=>	"Simcoe®",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'aroma'			=>	"earthy, passion fruit, pine, berry ",
			'substitutions'			=>	'["Summit","Magnum","Amarillo","Cascade","Centennial"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"US-Style Ales, Pale Ales, IPAs, Double IPAs",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"132",
			'variety'			=>	"Smaragd",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"Germany",
			'aroma'			=>	"floral, spicy and mild fruity.",
			'substitutions'			=>	'["Hallertau Mittelfruh"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Ale, Amber, Pilsners, German Ales, German Lagers, Belgian Styles, Weissbier",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"133",
			'variety'			=>	"Sorachi Ace",
			'alpha_min'			=>	"11.5",
			'alpha_max'			=>	"14.5",
			'origin'			=>	"United States",
			'aroma'			=>	"lemon, lime and dill.",
			'substitutions'			=>	'["Southern Cross"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Saison",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"134",
			'variety'			=>	"Southern Brewer",
			'alpha_min'			=>	"9.0",
			'alpha_max'			=>	"10.5",
			'origin'			=>	"South Africa",
			'substitutions'			=>	'["Southern Promise"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pilsner, Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"135",
			'variety'			=>	"Southern Cross",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.6",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"citrus, tropical fruits with hints of lemon zest, lime, pine and spice",
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Pale Ale, IPA, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"136",
			'variety'			=>	"Southern Promise",
			'alpha_min'			=>	"9.5",
			'alpha_max'			=>	"11.5",
			'origin'			=>	"South Africa",
			'aroma'			=>	"subtle woody, earthy, bright, smooth, bitterness",
			'substitutions'			=>	'["Southern Brewer"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lager, Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"137",
			'variety'			=>	"Sovereign",
			'alpha_min'			=>	"4.5",
			'alpha_max'			=>	"6.5",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"pleasant but intense fruity flavors with mild floral, grassy, herbal and mint characteristics.",
			'substitutions'			=>	'["Fuggle"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"American Lager, American Pale Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"138",
			'variety'			=>	"Status ",
			'alpha_min'			=>	"12.5",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'purpose'			=>	"Dual Purpose",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"139",
			'variety'			=>	"Sterling",
			'alpha_min'			=>	"6.0",
			'alpha_max'			=>	"9.0",
			'origin'			=>	"United States",
			'aroma'			=>	"noble & spicy",
			'substitutions'			=>	'["Saaz"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"IPA",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"140",
			'variety'			=>	"Sticklebract",
			'alpha_min'			=>	"13.0",
			'alpha_max'			=>	"14.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"pine, citrus aromas",
			'substitutions'			=>	'["Northern Brewer"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"ESB",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"141",
			'variety'			=>	"Super Alpha",
			'alpha_min'			=>	"12.5",
			'alpha_max'			=>	"15.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"Grass, pine and citrus flavors",
			'substitutions'			=>	'["Green Bullet"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lagers, Pilsners, Bitters",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"142",
			'variety'			=>	"Super Pride",
			'alpha_min'			=>	"14.0",
			'alpha_max'			=>	"15.0",
			'origin'			=>	"Australia",
			'aroma'			=>	"mild and pleasant subtle resin and fruit tones.",
			'substitutions'			=>	'["Pride of Ringwood"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Imperial Pale Ale, Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"143",
			'variety'			=>	"Super Styrian (Aurora)",
			'alpha_min'			=>	"7.5",
			'alpha_max'			=>	"8.8",
			'origin'			=>	"Slovenia",
			'aroma'			=>	"noble characteristics",
			'substitutions'			=>	'["Styrian Golding","Northern Brewer"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"American Pale Ale, Dark Lager",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"144",
			'variety'			=>	"Waimea",
			'alpha_min'			=>	"16.0",
			'alpha_max'			=>	"19.0",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"pine, citrus, tangelo",
			'substitutions'			=>	'["Columbus","Pacific Jade"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"India Pale Ale, Pale Ale, Lagers",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"145",
			'variety'			=>	"Wakatu",
			'alpha_min'			=>	"6.5",
			'alpha_max'			=>	"8.5",
			'origin'			=>	"New Zealand",
			'aroma'			=>	"understated floral notes and citrusy lime aromas",
			'substitutions'			=>	'["Hallertauer Mittelfrüh","Nelson Sauvin"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Lager, Pale Ale, Belgian Ale",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"146",
			'variety'			=>	"WGV",
			'alpha_min'			=>	"5.4",
			'alpha_max'			=>	"7.7",
			'origin'			=>	"United Kingdom",
			'aroma'			=>	"earthy, botanical, floral, sweet fruit flavor",
			'substitutions'			=>	'["Fuggle","Styrian Golding","East Kent Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Bitter, Scottish Ale, Pale Ale, Best Bitter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"147",
			'variety'			=>	"Willamette",
			'alpha_min'			=>	"4.0",
			'alpha_max'			=>	"6.0",
			'origin'			=>	"United States",
			'aroma'			=>	"floral, incense, and elderberry aromas",
			'substitutions'			=>	'["Fuggle","Styrian Golding","Tettnanger (US)","Glacier","Styrian Golding"]',
			'purpose'			=>	"Dual Purpose",
			'styles'			=>	"Ale, American Ales, Pale Ale, Brown Ale, English Ales, Porter",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"148",
			'variety'			=>	"Azacca",
			'alpha_min'			=>	"12.0",
			'alpha_max'			=>	"14.0",
			'origin'			=>	"United States",
			'aroma'			=>	"Aromas of tropical fruits and citrus. Tasting notes of spicy mango, pineapple, tangerine and pine.",
			'purpose'			=>	"Dual Purpose",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"149",
			'variety'			=>	"Jarrylo",
			'alpha_min'			=>	"15.0",
			'alpha_max'			=>	"17.0",
			'origin'			=>	"United States",
			'aroma'			=>	"Strong tones of fruit (banana, pear, melon, orange) with spicy and grassy notes.",
			'purpose'			=>	"Dual Purpose",
			'descriptions'			=>	"null",
		]);
		DB::table('hjp_brouwerbouwer_hop_adjunct_list')->insert([
			'id'			=>	"150",
			'variety'			=>	"Coconut Flakes",
			'alpha_min'			=>	"0.0",
			'alpha_max'			=>	"0.0",
			'origin'			=>	"N.v.t.",
			'purpose'			=>	"Aroma",
			'descriptions'			=>	"null",
		]);
	}
}