list: $/hjp/brouwerbouwer/models/gear/columns.yaml
modelClass: Hjp\Brouwerbouwer\Models\Gear
title: Gear
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hjp/brouwerbouwer/gear/update/:id'
