name: MashScheme
form: $/hjp/brouwerbouwer/models/mashscheme/fields.yaml
modelClass: Hjp\Brouwerbouwer\Models\MashScheme
defaultRedirect: hjp/brouwerbouwer/mashscheme
create:
    redirect: 'hjp/brouwerbouwer/mashscheme/update/:id'
    redirectClose: hjp/brouwerbouwer/mashscheme
update:
    redirect: hjp/brouwerbouwer/mashscheme
    redirectClose: hjp/brouwerbouwer/mashscheme
